### ISSUE TITLE
错别字 

### ISSUE THREAD

**Issue by lietoumai** [phodal/make#4]
适应微服务架构
如我们所见在最近几年里看到的那样，微服务并不没有大量地替换掉单体应用——毕竟使用新的架构来替换旧的系统，在业务上的价值并不大。因此，对于很多企业来说，并没有这样的强烈需求及紧迫性。活着，才是一件更紧迫的事。

微服务并不没有大量地替换掉单体应用

是不是应该改为

微服务并没有大量地替换掉单体应用

**Comment by phodal** [comment]
谢谢

**Comment by lietoumai** [comment]
> 谢谢

不客气，我昨天发你邮件了，但是没看到回复，怕你没看到
所以这里提一下😄
